var namespace_mono_1_1_addins_1_1_description =
[
    [ "AddinDependency", "class_mono_1_1_addins_1_1_description_1_1_addin_dependency.html", "class_mono_1_1_addins_1_1_description_1_1_addin_dependency" ],
    [ "AddinDescription", "class_mono_1_1_addins_1_1_description_1_1_addin_description.html", "class_mono_1_1_addins_1_1_description_1_1_addin_description" ],
    [ "AddinFileInfo", "class_mono_1_1_addins_1_1_description_1_1_addin_file_info.html", "class_mono_1_1_addins_1_1_description_1_1_addin_file_info" ],
    [ "AddinProperty", "class_mono_1_1_addins_1_1_description_1_1_addin_property.html", "class_mono_1_1_addins_1_1_description_1_1_addin_property" ],
    [ "AddinPropertyCollection", "interface_mono_1_1_addins_1_1_description_1_1_addin_property_collection.html", "interface_mono_1_1_addins_1_1_description_1_1_addin_property_collection" ],
    [ "AddinPropertyCollectionImpl", "class_mono_1_1_addins_1_1_description_1_1_addin_property_collection_impl.html", "class_mono_1_1_addins_1_1_description_1_1_addin_property_collection_impl" ],
    [ "AssemblyDependency", "class_mono_1_1_addins_1_1_description_1_1_assembly_dependency.html", "class_mono_1_1_addins_1_1_description_1_1_assembly_dependency" ],
    [ "ConditionTypeDescription", "class_mono_1_1_addins_1_1_description_1_1_condition_type_description.html", "class_mono_1_1_addins_1_1_description_1_1_condition_type_description" ],
    [ "ConditionTypeDescriptionCollection", "class_mono_1_1_addins_1_1_description_1_1_condition_type_description_collection.html", "class_mono_1_1_addins_1_1_description_1_1_condition_type_description_collection" ],
    [ "Dependency", "class_mono_1_1_addins_1_1_description_1_1_dependency.html", "class_mono_1_1_addins_1_1_description_1_1_dependency" ],
    [ "DependencyCollection", "class_mono_1_1_addins_1_1_description_1_1_dependency_collection.html", "class_mono_1_1_addins_1_1_description_1_1_dependency_collection" ],
    [ "Extension", "class_mono_1_1_addins_1_1_description_1_1_extension.html", "class_mono_1_1_addins_1_1_description_1_1_extension" ],
    [ "ExtensionCollection", "class_mono_1_1_addins_1_1_description_1_1_extension_collection.html", "class_mono_1_1_addins_1_1_description_1_1_extension_collection" ],
    [ "ExtensionNodeDescription", "class_mono_1_1_addins_1_1_description_1_1_extension_node_description.html", "class_mono_1_1_addins_1_1_description_1_1_extension_node_description" ],
    [ "ExtensionNodeDescriptionCollection", "class_mono_1_1_addins_1_1_description_1_1_extension_node_description_collection.html", "class_mono_1_1_addins_1_1_description_1_1_extension_node_description_collection" ],
    [ "ExtensionNodeSet", "class_mono_1_1_addins_1_1_description_1_1_extension_node_set.html", "class_mono_1_1_addins_1_1_description_1_1_extension_node_set" ],
    [ "ExtensionNodeSetCollection", "class_mono_1_1_addins_1_1_description_1_1_extension_node_set_collection.html", "class_mono_1_1_addins_1_1_description_1_1_extension_node_set_collection" ],
    [ "ExtensionNodeType", "class_mono_1_1_addins_1_1_description_1_1_extension_node_type.html", "class_mono_1_1_addins_1_1_description_1_1_extension_node_type" ],
    [ "ExtensionNodeTypeCollection", "class_mono_1_1_addins_1_1_description_1_1_extension_node_type_collection.html", "class_mono_1_1_addins_1_1_description_1_1_extension_node_type_collection" ],
    [ "ExtensionPoint", "class_mono_1_1_addins_1_1_description_1_1_extension_point.html", "class_mono_1_1_addins_1_1_description_1_1_extension_point" ],
    [ "ExtensionPointCollection", "class_mono_1_1_addins_1_1_description_1_1_extension_point_collection.html", "class_mono_1_1_addins_1_1_description_1_1_extension_point_collection" ],
    [ "ModuleCollection", "class_mono_1_1_addins_1_1_description_1_1_module_collection.html", "class_mono_1_1_addins_1_1_description_1_1_module_collection" ],
    [ "ModuleDescription", "class_mono_1_1_addins_1_1_description_1_1_module_description.html", "class_mono_1_1_addins_1_1_description_1_1_module_description" ],
    [ "NativeDependency", "class_mono_1_1_addins_1_1_description_1_1_native_dependency.html", "class_mono_1_1_addins_1_1_description_1_1_native_dependency" ],
    [ "NodeSetIdCollection", "class_mono_1_1_addins_1_1_description_1_1_node_set_id_collection.html", "class_mono_1_1_addins_1_1_description_1_1_node_set_id_collection" ],
    [ "NodeTypeAttribute", "class_mono_1_1_addins_1_1_description_1_1_node_type_attribute.html", "class_mono_1_1_addins_1_1_description_1_1_node_type_attribute" ],
    [ "NodeTypeAttributeCollection", "class_mono_1_1_addins_1_1_description_1_1_node_type_attribute_collection.html", "class_mono_1_1_addins_1_1_description_1_1_node_type_attribute_collection" ],
    [ "ObjectDescription", "class_mono_1_1_addins_1_1_description_1_1_object_description.html", "class_mono_1_1_addins_1_1_description_1_1_object_description" ],
    [ "ObjectDescriptionCollection", "class_mono_1_1_addins_1_1_description_1_1_object_description_collection.html", null ]
];